### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by mathrick** [algolia/github-awesome-autocomplete#1]
Any chance of having it ported to Firefox?

**Comment by asurak** [comment]
Working on it ;)

**Comment by mathrick** [comment]
Awesome, thanks!

**Comment by redox** [comment]
Should be reviewed by Mozilla's team in the next few days :)

**Comment by seafoox** [comment]
Hi @mathrick,
The extension is now available https://addons.mozilla.org/fr/firefox/addon/github-awesome-autocomplete/
Feel free to give a try and share your feedbacks in a new thread.

Enjoy!
