### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by rimenes** [algolia/github-awesome-autocomplete#10]
Some characters in the search result appear as mojibakes

![mojibake](https://www.evernote.com/shard/s31/sh/756b6dd1-ae84-428a-8526-be3442dbbe50/81804192d80cb10d59d05881be5b0b2b/res/5bb4c527-f3dc-48ac-b6bd-c9676a3367df/skitch.png?resizeSmall&width=832)

**Comment by lichunqiang** [comment]
I just want report this :+1:

**Comment by redox** [comment]
Hey @rimenes & @lichunqiang,

thank you very much for reporting us that. That's actually an issue of the underlying database I'm using to index the data. I've reported it to Githubarchive: https://github.com/igrigorik/githubarchive.org/issues/60 but if I'm right, the existing data can not really be fixed :/

I'm keeping this one open, maybe we'll end up having our own database.

**Comment by redox** [comment]
So we now use the new GitHubArchive tables which should help fixing those encoding issues (should be fixed for every single activity after 2015/1/1).

**Comment by rimenes** [comment]
Awesome
