### ISSUE TITLE
Documentation on the issues enhancement? 

### ISSUE THREAD

**Issue by EdgeCaseBerg** [algolia/github-awesome-autocomplete#16]
The README says: 

    This extension replaces GitHub's search bar and add auto-completion (instant-search & suggestion)   
    capabilities on:
    ...
    - your issues (only available if you choose to "Connect with GitHub")

But after clicking the magnifying glass and allowing algolia via oauth, I didn't see any change on issue's page search boxes or anything like that. Is there something more to having issues be searchable? Could we have more documentation on what this is supposed to look like?

**Comment by redox** [comment]
Hi @EdgeCaseBerg, oh yes you should :/ I think I found the issue -> the GitHub API was returning a non-handled error if I tried to access a disabled project (your GamerGateOP fork). Can you retry now and let me know if it's working?

**Comment by EdgeCaseBerg** [comment]
It's working now! Very cool!
