### ISSUE TITLE
Automenu doesn't work as it normally would (twitching)

### ISSUE THREAD

**Issue by jeroenvisser101** [algolia/github-awesome-autocomplete#19]
Hi there,

Kudo's for the extension, really like it. It seems however that since the latest update, the autocomplete menu twitches a bit. I've tried to capture that in the screencast below.

![](https://www.dropbox.com/s/753ou7q4csf6w8t/autocomplete-bug.gif?dl=1)

Please let me know if I can help!

**Comment by redox** [comment]
Hey @jeroenvisser101,

yes it definitely helps, thank you for the report. I'll work on it during the next days.

**Comment by jeroenvisser101** [comment]
Cool! Amazingly fast, appreciate it!

**Comment by redox** [comment]
And from the airport btw :smile: :airplane:

**Comment by jeroenvisser101** [comment]
Ha! Have a good flight (if you are going to fly, that is) :smile:

**Comment by jeroenvisser101** [comment]
Very nice, thanks!
