### ISSUE TITLE
.icon-delete style visibility

### ISSUE THREAD

**Issue by ozlerhakan** [algolia/github-awesome-autocomplete#21]
Hi,
In Chrome, when I hover the search area as described in the below image, the cursor changes to a hand on the specific area. Perhaps, the .icon-delete style [on line 225](https://github.com/algolia/github-awesome-autocomplete/blob/c6d5ae6addeb1718330d8270e1ccb67a555f01f7/code/css/content.css#L225) needs as well the visibility property as 'hidden' and also this property must be 'visible' alongside the opacity property [on line 238](https://github.com/algolia/github-awesome-autocomplete/blob/c6d5ae6addeb1718330d8270e1ccb67a555f01f7/code/css/content.css#L238). 

![cursor](https://cloud.githubusercontent.com/assets/1964927/6063334/140903ba-ad5f-11e4-9a9e-edee1590276e.gif)

**Comment by Shipow** [comment]
Thank your for reporting us that!

**Comment by ozlerhakan** [comment]
You're welcome!
