### ISSUE TITLE
Broken layout search field

### ISSUE THREAD

**Issue by jeroenvisser101** [algolia/github-awesome-autocomplete#22]
Currently, it seems that Algolia's plugin breaks the layout of the search field.

![](https://www.dropbox.com/s/7sw6rbowviiink2/Screenshot%202015-05-14%2011.05.04.png?dl=1)

**Comment by redox** [comment]
Arg, good catch! Recent regressions :/

**Comment by jeroenvisser101** [comment]
Yeah, seems like removing `display: inline-block` from the inline style for element `.twitter-typeahead` fixes this.

**Comment by jeroenvisser101** [comment]
See [this line](https://github.com/algolia/github-awesome-autocomplete/blob/master/code/js/libs/typeahead.bundle.js#L741)

**Comment by redox** [comment]
Yeah, it will not be enough; the expected behavior is then that the dropdown menu takes the whole input width.

**Comment by jeroenvisser101** [comment]
Ouch, than that might turn out to be a bit more work...

**Comment by jeroenvisser101** [comment]
Btw, this does not happen with search fields that are missing the tag 'This repository'

**Comment by redox** [comment]
Yep, I'm currently re-reading the code and cannot understand how it could have worked before :+1:

**Comment by redox** [comment]
Should be better like that; now release time :p

**Comment by jeroenvisser101** [comment]
Hah, nice, thanks for the super quick fix!

**Comment by redox** [comment]
You're welcome @jeroenvisser101, thanks for the bug report & investigation.

"Your item is in the process of being published and may take up to 60 minutes to appear in the Chrome Web Store."

**Comment by jeroenvisser101** [comment]
@redox update is in, it now work way better! However, it still adds like 2px under the label after the extension loaded, but that's okay for now :+1:
