### ISSUE TITLE
Stacking input below scope-badge

### ISSUE THREAD

**Issue by dhamaniasad** [algolia/github-awesome-autocomplete#23]
It seems like this plugin is causing the input on the search field to stack below the scope-badge. This is what it looks like:

![](http://i.imgur.com/1pRzy7F.png)

I've tried disabling all my plugins but GitHub Awesome Autocomplete, and I am certain this plugin is causing it. 

It seems like [this](https://github.com/algolia/github-awesome-autocomplete/blob/9582c282ff285be95e4af1cba89312cf0fe5468c/code/js/libs/typeahead.bundle.js#L741) is the line of code(in the typehead library) that is causing this issue.

**Comment by redox** [comment]
Hi @dhamaniasad, this issue has been reported yesterday (https://github.com/algolia/github-awesome-autocomplete/issues/22) and has been fixed in 1.1.3 -> it's already released on Chrome but not yet reviewed on Firefox. Are you using Firefox?

**Comment by dhamaniasad** [comment]
@redox I just updated the extension to 1.1.3 on Chrome, and the issue seems to have resolved, apart from the extra 2px on the bottom as mentioned on #22. Thanks for the quick fix for this issue :).

**Comment by redox** [comment]
Alright, good news :)
