### ISSUE TITLE
Star and heart icons are missing on Chrome

### ISSUE THREAD

**Issue by danmana** [algolia/github-awesome-autocomplete#29]
The star and heart icons do not show up on Chrome (version 48.0.2564.109 m).

I noticed that in my case the other github icons on the page (that work) are implemented as svg, not using the octicon icon font ...

![missing-icons](https://cloud.githubusercontent.com/assets/498419/13049423/7894fbd2-d3f5-11e5-9719-44084ef1b041.png)

**Comment by Shipow** [comment]
ha! Good catch, we'll fix that.
Thanks for the report (very) much appreciated.

**Comment by danmana** [comment]
Works great now. Thanks for the fix :)

**Comment by redox** [comment]
Thanks for following up @danmana :100:
