### ISSUE TITLE
Safari port?

### ISSUE THREAD

**Issue by redox** [algolia/github-awesome-autocomplete#3]
Need to check how that could be done; hopefully easier than Firefox :)

**Comment by nesl247** [comment]
Would be interested in this as well.

**Comment by redox** [comment]
Done \o/

**Comment by ashfurrow** [comment]
:tada:

**Comment by redox** [comment]
Does it work as expected @ashfurrow? I tried to submit it to the official Safari Extension directory but encounter a few issues :/ Quick fix was to provide you guys the `.safariextz` file :/

**Comment by ashfurrow** [comment]
Yeah, it worked no problem! When I opened the `.sarafiextz` it asked me if I wanted to trust the source of it, but that was all.

**Comment by ashfurrow** [comment]
Thanks a lot for working on it! I subscribed to this issue ages ago and had forgotten about it until I got the notification this morning. Excellent work!

**Comment by redox** [comment]
Awesome @ashfurrow; thank you for the follow up :) Btw, we've updated the underlying index and we've now the whole directory of users + most recent projects \o/
