### ISSUE TITLE
Update the API client version

### ISSUE THREAD

**Issue by seafoox** [algolia/github-awesome-autocomplete#30]
For now the extension is using an old version of the JS API client. That one doesn't include the DSN logic required in case of DNS issue.

`var ALGOLIA_VERSION = '2.8.5';`

**Comment by redox** [comment]
Yes we should move to 3.0; I'm just a bit afraid of the Firefox validation -> last time they read all the code and I manually needed to remove the JSONP-related snippet of code for security reason.

**Comment by redox** [comment]
See https://github.com/algolia/github-awesome-autocomplete/blob/master/code/js/libs/algoliasearch.js#L627-L636

**Comment by rayrutjes** [comment]
I think we should not do the move for now.
It would indeed be a problem for the different market places.
Maybe with the client in V4 we could just include the strict minimum required that would not raise an alert during the reviewing processes on the different marketplaces.
