### ISSUE TITLE
The search bar breaks in two lines when in a repository

### ISSUE THREAD

**Issue by hkdobrev** [algolia/github-awesome-autocomplete#32]
Since today the GitHub search bar is breaking down in two lines when inside of a repository. Disabling this extension removes the problem. I guess GitHub changed something.

![screen shot 2016-03-17 at 12 10 54](https://cloud.githubusercontent.com/assets/506129/13842909/5483e5da-ec39-11e5-9509-ba50bfedbcd7.png)

**Comment by LukyVj** [comment]
Thanks, a fix is on it's way.
