### ISSUE TITLE
[Suggestion] Dark theme

### ISSUE THREAD

**Issue by charlesmilette** [algolia/github-awesome-autocomplete#34]
[StylishThemes/GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) is a CSS style for theming GitHub to dark.

The addon doesn't gives well combined with the style:
![capture](https://cloud.githubusercontent.com/assets/6440374/13990137/a00da374-f0e9-11e5-9f7d-21b930aad646.PNG)
Any possibility to add a dark theme?

**Comment by redox** [comment]
Definitely :) Not sure if the best wouldn't be to submit a PR on [StylishThemes/GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) ?

@silverwind @Mottie what do you guys think?

**Comment by silverwind** [comment]
We already support a bunch of GitHub extensions in the theme, so I guess another one wouldn't hurt. If you feel up to it please submit a PR, otherwise please open an issue and we'll get to it eventually.

**Comment by redox** [comment]
Awesome @silverwind :+1: I'll definitely do that!

**Comment by charlesmilette** [comment]
Opened a issue on the theme repo:
https://github.com/StylishThemes/GitHub-Dark/issues/298

**Comment by rayrutjes** [comment]
Enjoy!

**Comment by redox** [comment]
Thank you @rayrutjes :+1:
