### ISSUE TITLE
Does not work after having filtered on a language

### ISSUE THREAD

**Issue by rayrutjes** [algolia/github-awesome-autocomplete#38]
When on a repository search page, if we filter by language, the search is reloaded asynchronously which breaks the bindings.

Maybe we could delegate the binding to a higher level in the dom tree?

![image](https://cloud.githubusercontent.com/assets/5570853/14006025/26984e74-f169-11e5-8894-1af8b849323c.png)

**Comment by redox** [comment]
Hmmm, good catch :/

But what should we do since we don't have the data to provide a faceted search based on the language :/ Breaking the binding is now good, but I'm wondering if we want to show the dropdown menu to the user once he selected a language :/

**Comment by rayrutjes** [comment]
You are right. I think breaking the binding makes sense actually as we do not have language as facet. Feel free to close.
