### ISSUE TITLE
No border on search input on Firefox

### ISSUE THREAD

**Issue by rayrutjes** [algolia/github-awesome-autocomplete#39]
The following statement seems to be the source of the trouble: https://github.com/algolia/github-awesome-autocomplete/blob/0017ca44361ca47c83a8b41ef3478fd1fe32c8ca/code/scss/content.sass#L70-L71

StylishThemes/GitHub-Dark#302

**Comment by LukyVj** [comment]
Hi @rayrutjes thanks for pointing this out! 
We'll investigate!

**Comment by redox** [comment]
And thank you so much for https://github.com/StylishThemes/GitHub-Dark/pull/302 :+1:

**Comment by rayrutjes** [comment]
My pleasure @redox .
Can you guys tell me what these statements target, are they still useful?
```
form#search_form .awesome-autocomplete .twitter-typeahead .tt-input {
    border-color: #343434 !important;
  }
  form#search_form .awesome-autocomplete .twitter-typeahead .tt-input:focus {
    border-color: #51A7E8 !important;
  }
```

**Comment by LukyVj** [comment]
@rayrutjes I don't think so, AFAIK the `#search_form` id was replaced by `#js-site-search-form`

**Comment by rayrutjes** [comment]
@LukyVj That is what I thought. Thx.

**Comment by rayrutjes** [comment]
Do you want me to make a PR for this one? Or already working on it?

**Comment by LukyVj** [comment]
If you already got the solution in your hand, I'd say go for a PR :) 
cc @redox

**Comment by rayrutjes** [comment]
Actually I got to go, but if no one tackles this, I'll do it tonight.
