### ISSUE TITLE
Deleted repos still appears in "Your Repositories" section

### ISSUE THREAD

**Issue by ushuz** [algolia/github-awesome-autocomplete#43]
![image](https://cloud.githubusercontent.com/assets/1430856/15361855/d8afdc14-1d45-11e6-93ff-3da5eaf4eb46.png)

The repo in picture was removed two days ago, but it still appears in search results.

**Comment by redox** [comment]
Thank you for reporting that. I need to re-work a bit the way we index own repositories to fix those synchronization issue.

**Comment by Mottie** [comment]
It's not just *own* repositories... If you search for "codepen", the no-longer-existing "CodePen/CodePen" repo is listed

![2016-07-11 18_19_38-codepen](https://cloud.githubusercontent.com/assets/136959/16750052/5f62aa7a-4794-11e6-8f72-c32ef07c3a10.png)

**Comment by kidonng** [comment]
Same problem for renamed repos. It's the only issue with this awesome plugin. @redox @rayrutjes Do you still maintain this project?

**Comment by rayrutjes** [comment]
Hi @kidonng ,

Thanks for the feedback, we are aware of those issues and we hope to address those early next year.

Thanks for your patience!

**Comment by ushuz** [comment]
The project seems abandoned.
