### ISSUE TITLE
autocomplete in Firefox search/awesome bar?

### ISSUE THREAD

**Issue by drewda** [algolia/github-awesome-autocomplete#44]
I have GitHub set up as a search engine in the Firefox "awesome bar" with a prefix of `gh`:

![monosnap 2016-05-31 08-45-05](https://cloud.githubusercontent.com/assets/212369/15680853/ff63f172-270b-11e6-8579-8b997f5dc52d.png)

Would it be possible to use this add-on to autocomplete as I type there?

**Comment by redox** [comment]
> Would it be possible to use this add-on to autocomplete as I type there?

I don't know the Firefox address bar API enough but it seems to be somehow possible to hook into it to add suggestions (see what https://github.com/estivo/Instantfox does).

Any pull-request is very welcome and I would love to assist you 👍

**Comment by rayrutjes** [comment]
Hey @drewda ,

As much as I like the idea, I don't think we want to implement this.

This would require us to expose a search endpoint on our end and hack the opensearch mechanism to add a new plugin to fetch results from there.

If you have a better idea in mind please let us know.

Also, I feel like so far opensearch isn't that used, probably because the UX of the address bar kinda hides this feature from users.

**Comment by rayrutjes** [comment]
Hmmm, I actually found something worth experimenting, let's leave it open a bit longer 🤓

**Comment by sammarcus** [comment]
@rayrutjes this is a really cool new feature, but may I humbly suggest there be a way to disable it? several times a day I run google searches about american airlines ("`aa`") and I'm no longer able to do this from the omnibox without the extension taking over.

or, alternatively, do you know how to redirect text input back to normal, after an extension has control in the omnibox? I've tried hitting escape key but that clears the entire input, and backspace temporarily works but as soon as a space is added after your keyword it brings it back to the extension input.

thank you!

**Comment by rayrutjes** [comment]
Wow that's unfortunate @sammarcus .
I'll take a look to see what we can do.

**Comment by sammarcus** [comment]
thank you! I know it's an (extreme) edge case, thanks for your consideration 🙏🏼😇

**Comment by rayrutjes** [comment]
@sammarcus I went through all chrome settings and it seems to be impossible to either change/override the shortcut nor disable just the omnibox part.

As a workaround, what I can suggest is: 
- clone this repo
- edit the `content/chrome.js` file and change the `aa` shortcut to whatever you want (or disable it by removing it)
- install grunt and run `grunt`
- then from `chrome://extensions` enable developer mode and load the `build/unpacked-prod` directory as an "unpacked extension".

Let me know if that could work for you.
I'll help you along the road if you have an issue getting this manually loaded.
