### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by ogirginc** [algolia/github-awesome-autocomplete#45]
Tried by disabling all other extensions but didn't help (works as expected on Chrome).

- Safari 9.1.1
- Mac OS X 10.11.5

**Comment by redox** [comment]
Arg :/ I'll check what I can do, seems a recent regression.

**Comment by ogirginc** [comment]
Just found out; it works on Safari, if I use [https://github.com/search](https://github.com/search) to search.

**Comment by redox** [comment]
Alright, so it might only be a CSS selector issue. I'll try to check tonight.

**Comment by ogirginc** [comment]
If it does help, Safari's console gave me this error:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com". (search, line 0)

```
<div class="aa-query">
  "Press "
  <em><Enter></em>
  " to "
  <span class="aa-query-default">
      "search for ""
      <em>asdf</em>
      """
  </span>
  <span class="aa-query-cursor"></span>
</div> = $1
```

**Comment by phyllisstein** [comment]
I was having the same issue, and discovered something interesting in the course of troubleshooting it: `HEAD` is at version 1.2.6, but the download links in the README and on the website all point to version 1.2.0. The direct-from-source build works great for me.

**Comment by redox** [comment]
> I was having the same issue, and discovered something interesting in the course of troubleshooting it: HEAD is at version 1.2.6, but the download links in the README and on the website all point to version 1.2.0. The direct-from-source build works great for me.

Good catch @phyllisstein; and I now remember I couldn't package the Safari extension since a while because of a bug in Safari 9.1 (cannot find the support forum explaining it right now, but it couldn't find the Safari Developer profile).

This is now fixed and you can download it from https://github.algolia.com/github-awesome-autocomplete.safariextz
