### ISSUE TITLE
GitHub Awesome Autocomplete only works on search page

### ISSUE THREAD

**Issue by JohJakob** [algolia/github-awesome-autocomplete#47]
In Safari 9 and 10 on OS X El Capitan, the extension only works in the search field on GitHub's search page (the search field is positioned in the main area and not in the top bar). When the search field is in the top bar, the extension's suggestion box is not shown.

**Comment by redox** [comment]
Hi @JohJakob, thank you for your help invetigating. It looks like this is #45. Definitely something I need to work on but didn't have the time yet :/
