### ISSUE TITLE
doesn't refresh repositories

### ISSUE THREAD

**Issue by nickjer** [algolia/github-awesome-autocomplete#48]
If I add a new public or private repository it doesn't show up in the search.

If I click

![image](https://cloud.githubusercontent.com/assets/4260509/16732787/d1ba1998-474c-11e6-8437-74f80246a007.png)

the button does not seem clickable (it behaves like a static image, i.e., doesn't pop in when click and pop out after click). Button animation aside, even if I click the button it doesn't refresh the repositories. Only way to refresh repositories is to uninstall/reinstall Chrome extension.

I am using:
- Google Chrome version 53.0.2783.2 (64-bit)
- Ubuntu 16.04

**Comment by redox** [comment]
Thanks for reporting us that @nickjer. I didn't use the refresh button since a while, I'll give it a try to see if we have a regression.

**Comment by zaininfo** [comment]
I can confirm that around the time this issue was reported, there was a workaround involving removing & adding back the extension.
But, that workaround seems to have stopped working too.

@redox could you please, provide an update on this, if any.

**Comment by redox** [comment]
> I can confirm that around the time this issue was reported, there was a workaround involving removing & adding back the extension.
> But, that workaround seems to have stopped working too.
> 
> @redox could you please, provide an update on this, if any.

Didn't take the time to work on it so far. I'll give it a try in the next few days.
