### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by stuart-lang** [algolia/github-awesome-autocomplete#49]
Love this extension!
Would it be feasible to have an offering that indexes a GitHub Enterprise instance instead of github.com?

**Comment by redox** [comment]
> Would it be feasible to have an offering that indexes a GitHub Enterprise instance instead of github.com?

Oh yeah sure 👍  The easiest is probably to create your Algolia account with your private content (building a small script calling the GitHub API with your account and sending everything to Algolia) and then forking that extension to update the underlying credentials.

Would that work for you? I'm happy to help make that happen, just email sylvain at algolia :)

**Comment by stuart-lang** [comment]
Thanks, that's what I was expecting the process to be, wasn't sure if you had the code that calls the GitHub API and sends it to Algolia around somewhere. I'm probably going to hack something together next month, I plan on also adding file names and extracting type declarations from code.

**Comment by redox** [comment]
> Thanks, that's what I was expecting the process to be, wasn't sure if you had the code that calls the GitHub API and sends it to Algolia around somewhere. I'm probably going to hack something together next month, I plan on also adding file names and extracting type declarations from code.

Awesome, let me know how that goes then :)

I'll close this issue in the meantime 👍
