### ISSUE TITLE
Cleared value is restored on blur

### ISSUE THREAD

**Issue by Mottie** [algolia/github-awesome-autocomplete#51]
If I start a search, clear the content using the button inside the input, then blur the input.... the search I entered is restored.

![autocomplete](https://cloud.githubusercontent.com/assets/136959/22848236/afd58e2e-efb8-11e6-94a3-57e63d78efc1.gif)

The "aw" was cleared, but is then restored on blur (clicking outside the input).

**Comment by Shipow** [comment]
thanks for reporting, we'll fix that.

**Comment by redox** [comment]
This has been fixed in the latest 1.3.3
