### ISSUE TITLE
Support GH emojis

### ISSUE THREAD

**Issue by rayrutjes** [algolia/github-awesome-autocomplete#68]
![image](https://user-images.githubusercontent.com/5570853/32656996-50797f5c-c614-11e7-86b3-9934be8bf5e4.png)

**Comment by Haroenv** [comment]
the indexer is in Ruby right? https://github.com/github/gemoji could convert them to unicode

**Comment by rayrutjes** [comment]
You are right @Haroenv this has to be done at indexing time.
