### ISSUE TITLE
Provide a option change `this repository` to `all repository`

### ISSUE THREAD

**Issue by eromoe** [algolia/github-awesome-autocomplete#69]
Hello

I usually not tend to search keyword in `this repository` while I am in a repo.  

For example, I am in `github-awesome-autocomplete` report this feature request,  and then  I want to search github notification enhance ,  I have to click github home  icon to home  page to do the search.

**Comment by rayrutjes** [comment]
Hey @eromoe ,

Thanks for reaching out.

Is it this part you want to change?
![image](https://user-images.githubusercontent.com/5570853/32719375-72e3b154-c860-11e7-8b6e-17e66abb77b1.png)

This feature mimics the default GitHub behaviour.
If you press the return button multiple times however it will remove the current `repository` scope.

Let me know if that is not what you meant.

**Comment by eromoe** [comment]
I mean  provide a config option to change 

![image](https://user-images.githubusercontent.com/3938751/32720265-f8c71580-c89d-11e7-93f5-7cc1b3151c1a.png)

to

![image](https://user-images.githubusercontent.com/3938751/32720261-f2e5e754-c89d-11e7-85e4-6ebf1327e16b.png)

**Comment by rayrutjes** [comment]
I think I see what you mean.
You are searching for a repo, but don't find a suitable answer in the autocompleted results then you want to submit the request globally and not to the repo only.

I think that makes sense and best would probably be to add a suggestion a second choice of the dropdown.

I don't think we will add "options" for now because it requires more setup but definitely something we could do in the future.

**Comment by rayrutjes** [comment]
@eromoe what do you think of #70 ? Was that what you had in mind?

**Comment by eromoe** [comment]
A little different , 

## Provide Config Option Would be good

Right click `github-awesome-autocomplete` icon

![image](https://user-images.githubusercontent.com/3938751/32756411-dbe92f62-c914-11e7-9627-85731577c30c.png)

the second grey out menu item  is  option. 

I would feel better to go into option and choose the behavious of the search box in a repository.

##  Default Search Box Behavious

1. Default behavious is like you  PR

    ![image](https://user-images.githubusercontent.com/3938751/32756380-b616a2ba-c914-11e7-8d9c-9831e3a596ca.png)

    -  Press  "Enter" to search xxx in *this repo*
    -  there is a `this repository` in front of search box

2. But I can change default behavious to 

    -  Press  "Enter" to search xxx in *all repo*
    -  no `this repository` in front of search box  (default search all repo)

**Comment by rayrutjes** [comment]
Hey @eromoe ,

I think that this feature alone does not justify the additional dedicated options page.

Also, our initial idea here was that the default "enter" mimics the GitHub behaviour.
If you want to search globally you could also always start by removing the "This repository" label.

I'll leave this open here to see if more users are interested.

**Comment by rayrutjes** [comment]
Solved by #76 .
