### ISSUE TITLE
Search `This Repository`

### ISSUE THREAD

**Issue by dcflow** [algolia/github-awesome-autocomplete#78]
Hello,

Did you guys build the `This Repository` search feature or is it from GitHub?

![fireshot capture 17 - jedwatson_react-select_ a select_ - https___github com_jedwatson_react-select_](https://user-images.githubusercontent.com/6751025/38149856-a77f5dc4-345c-11e8-90d2-96e8d95b8847.png)
It's strange cause it disappeared today.

Thank You!

**Comment by rayrutjes** [comment]
Hey,

No this is a GitHub feature.
Indeed, it disappeared! hadn't noticed the change myself.

Now we got to re-work our design :/

![image](https://user-images.githubusercontent.com/5570853/38150957-9fe2649e-3461-11e8-9ab4-e4d989ec250c.png)

**Comment by dcflow** [comment]
Probably it's temporary cause `This organization` works.

**Comment by rayrutjes** [comment]
> Probably it's temporary cause This organization works.
🤞 

Thanks for pinging us in case!

**Comment by pixelastic** [comment]
FWIW, "This repository" is back for me.
