### ISSUE TITLE
feature: search user's repos by language

### ISSUE THREAD

**Issue by davidosomething** [algolia/github-awesome-autocomplete#8]
in a user's repositories tab, there's a search field
add a filter by primary programming language used option

**Comment by rayrutjes** [comment]
Hey @davidosomething ,

I know your initial request is pretty old but I'd be interested to know a little more.

There is now a default instantsearch powered by GH itself, so I'm wondering if this still makes sense.

I'm closing this but please do re-open if you think it is still applies.
